export const FR_QUOTES: string[] = [
  "Apres tout, la moitié de la population est en dessous de la moyenne.",
  "Au village, c'est lui qui court après le facteur depuis que le chien est mort.",
  "C'est pas de sa faute si c'est pas marqué \"ne pas manger\" sur le shampoing.",
  "C'est pas la carpe la plus oxygénée du bassin.",
  "C'est pas la chips la plus croustillante du paquet.",
  "C'est pas la flèche la plus aiguisée du carquois.",
  "C'est pas la lumière la plus brillante du lustre.",
  "C'est pas la perle la plus brillante du collier.",
  "C'est pas la personne la plus conne du monde, mais il faudrait pas que l'autre meure.",
  "C'est pas la pomme la plus sucrée du verger.",
  "C'est pas le castor le plus utile au barrage.",
  "C'est pas le couteau le plus aiguisé du tiroir.",
  "C'est pas le fromage le plus affiné du terroir.",
  "C'est pas le kouign-amann le plus beurré de la vitrine.",
  "C'est pas le lampadaire qui éclaire le mieux l'allée.",
  "C'est pas le penguin qui glisse le plus loin.",
  "C'est pas le pigeon qui vole le plus haut.",
  "C'est pas le plus malin de la bande.",
  "C'est pas le plus rapide du peloton.",
  "C'est pas le processeur le mieux cadencé du marché.",
  "C'est pas le roi des cons, mais il a les clés du château.",
  "C'est pas le rosier le plus fleuri du jardin.",
  "C'est pas le saumon le plus vigoureux de l'atlantique.",
  "C'est pas le sommet le plus enneigé du massif.",
  "C'est pas le volcan le plus actif d'Auvergne.",
  "Il a 2 neurones qui se battent pour la 3ème place.",
  "Il a de la bonne mécanique, mais personne au volant.",
  "Il a des ampoules mais pas de lumière.",
  "Il a été démoulé trop chaud.",
  "Il a l'étincelle, mais la flamme s'est éteinte.",
  "Il a la boîte, mais pas les outils.",
  "Il a le pâté qui touche le couvercle.",
  "Il a les pieds sur terre, mais la tête en apesanteur.",
  "Il a pas inventé la machine a courber les bananes.",
  "Il a quelques trous dans la raquette.",
  "Il a toutes les pièces, mais le puzzle est mal monté.",
  "Il a un QI inférieur à la température ambiante.",
  "Il a une tête à connaître le goût des feutres.",
  "Il apporte un couteau en plastique à une bataille d'épées.",
  "Il brille pas plus qu'une bougie dans un tunnel.",
  "Il est difficile à sous-estimer.",
  "Il est difficile à suivre, mais facile à doubler.",
  "Il est du genre à chercher l'ombre dans une boîte d'allumettes.",
  "Il est du genre à éplucher les cailloux.",
  "Il est du genre à galérer pour vider l'eau d'une botte avec le mode d'emploi écrit sur le talon.",
  "Il est du genre à prendre une bouteille vide au cas où Il n'a pas soif.",
  "Il est du genre à secouer la tête quand on lui donne un éventail.",
  "Il est du genre à tirer le piano vers le tabouret.",
  "Il est gentil, mais j'en ferais pas un élevage.",
  "Il est monté comme une horloge, mais Il tourne à l'envers.",
  "Il fait des bulles sans avoir de savon.",
  "Il ferait un joli tableau de bord, mais sans moteur.",
  "Il irait plus loin si il démarrait en marche avant.",
  "Il lui manque 2 minutes de cuisson.",
  "Il n'a pas inventé la machine a courber les bananes.",
  "Il n'a pas inventé la pelle mais il en a prit un sacré coup.",
  "Il n'a pas inventé le cerf-volant, mais le vent le suit partout.",
  "Il n'a pas inventé le fil a couper le beurre.",
  "Il n'a pas la lumière à tous les étages.",
  "Il n'a pas toutes ses frites dans le même sachet.",
  "Il n'est pas assez vif pour courir après son ombre.",
  "Il n'est pas l'étoile la plus brillante de la galaxie.",
  "Il n'est pas la première crevette dans la paëlla.",
  "Il n'est pas le bouton le plus lumineux de la télécommande.",
  "Il n'est pas sorti de la dernière pluie, mais de la dernière bruine.",
  "Il pense pas plus vite qu'un escargot à contre-vent.",
  "Il raterait ses mains si il essayait d'applaudir.",
  "Il sait quel feutre a le meilleur goût.",
  "L'ascenseur ne monte pas jusqu'au dernier étage.",
  "La roue tourne, mais le hamster est mort.",
  "Les barrières sont baissées et les feux clignotent. Mais le train ne passe jamais.",
  "On l'aime bien au village, surtout depuis que le chien est mort.",
  "S'il pleuvait de la soupe Il sortirait avec une fourchette.",
  "Si l'intelligence est un bagage, Il voyage léger.",
  "Si la bêtise était une discipline olympique, Il aurait déjà la médaille d'or.",
  "Si la connerie se mesurait, Il servirait de mètre étalon.",
  "Si les cons étaient en orbite, Il arrêterait pas de tourner.",
  "Si les cons volaient, Il serait chef d'escadrille.",
  "Si on prenait tous les idiots du village pour les mettre dans le même village, Il serait toujours l'idiot du village.",
  "Son singe est tombé trop tôt de la branche.",
  "C'est pas le pingouin qui glisse le plus loin",
  "C'est pas la chips la plus croustillante du paquet",
  "C'est pas le hamster qui court le plus vite dans sa roue",
  "C'est pas le popcorn le plus éclaté du bol",
  "Il comprend vite, mais faut lui expliquer longtemps",
]
