# ============================================================
# Leksis — Multi-stage Dockerfile
# Base image: node:22-slim (Debian-based, not Alpine)
# Reason: @napi-rs/canvas requires glibc prebuilt binaries.
#         Alpine uses musl and would need extra system packages.
# ============================================================

# ── Stage 1: Install ALL dependencies (including devDeps for build) ──
FROM node:22-slim AS deps

WORKDIR /app

COPY package.json package-lock.json ./

# Install all dependencies — devDeps are needed by next build
# (TypeScript, PostCSS, Tailwind v4, etc.)
# Using npmmirror as registry fallback (npmjs.org may be unreachable on some networks)
RUN npm ci --registry https://registry.npmmirror.com


# ── Stage 2: Build the Next.js application ───────────────────
FROM node:22-slim AS builder

WORKDIR /app

# Reuse all deps from stage 1
COPY --from=deps /app/node_modules ./node_modules

# Copy all source files
COPY . .

ENV NEXT_TELEMETRY_DISABLED=1
ENV NODE_ENV=production

# These env vars are required at build time because db.ts / crypto.ts are
# imported statically by Next.js. They are never used for actual connections
# during the build — they only need to be syntactically valid.
ENV DATABASE_URL=postgresql://build:build@localhost:5432/build
ENV AUTH_SECRET=build-placeholder-not-used-in-production
ENV ENCRYPTION_KEY=0000000000000000000000000000000000000000000000000000000000000000
ENV NEXTAUTH_URL=http://localhost:3000

RUN npm run build


# ── Stage 3: Production runner ────────────────────────────────
FROM node:22-slim AS runner

WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

# Create a non-root user to run the application
RUN groupadd --system --gid 1001 nodejs \
 && useradd  --system --uid 1001 --gid nodejs nextjs

# Copy the standalone server output (includes server.js + minimal node_modules)
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./

# Copy static assets (CSS, JS chunks — not included in standalone output)
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

# Copy public folder (favicon, images, etc.)
COPY --from=builder --chown=nextjs:nodejs /app/public ./public

USER nextjs

EXPOSE 3000

ENV PORT=3000
ENV HOSTNAME=0.0.0.0

# server.js is generated by Next.js when output: 'standalone' is set in next.config.ts
CMD ["node", "server.js"]
